### ISSUE TITLE
Is sdmc.s required? and is a .cia build possible?

### ISSUE THREAD

**Issue by urherenow** [citra-emu/uncart#12]
This is on the front page "To build this, you will need to obtain a file called  sdmc.s  which implements the SDMC functionality as required by fatfs and place it in the  source/fatfs  folder."

Yet, I am able to build it without that file and end up with an arm9payload.bin and uncart.bin. I found 2 different sdmc.s files in other projects and when placing either where this tell me to, I am unable to build it with multiple definition errors.

Is using the arm9payload with brahma the only way to use this or can a .cia be created that will run from GW mode or rxTools with Pasta?

**Comment by archshift** [comment]
You need brahma/bootstrap no matter what. How you package brahma shouldn't matter though.
