### ISSUE TITLE
Project is likely not GPLv2

### ISSUE THREAD

**Issue by delroth** [citra-emu/uncart#8]
Or even open source, for that matter.

https://github.com/citra-emu/uncart/blob/master/source/fatfs/sdmc.s is a blatant disassembly of some other project, which I assume is some Nintendo code (I've never looked at Nintendo's 3DS stuff so I have no idea if it is -- but that sounds likely). This means this project is infringing on someone's copyright and definitely cannot be redistributed as GPLv2.

**Comment by neobrain** [comment]
The code was taken from Decrypt9, and I didn't notice that it was dubiously published and licensed.

@archshift Since you're the author of Decrypt9, could you shed some light on where this came from and whether we should get rid of it?

**Comment by archshift** [comment]
This code came from @Normmatt - and I was told it was not Nintendo's code, but likely Gateway's. Anyway, this is definitely an issue, sure.

**Comment by neobrain** [comment]
As a temporary provisional measure, I pruned the affected file from the whole repository. This means uncart will not compile as is, but at least we should be able to keep it up until a proper replacement is written.

**Comment by neobrain** [comment]
Fixed in 2f728ed5a1f7f322b via #9 .
